### PR TITLE
Apache license

### PR DESCRIPTION
**Pull request by bollu**
We accurately track the page with the `LICENSE` information, and we move from the MIT license to the Apache 2 license.

To accept this PR, we should receive acknowledgement from everyone who has contributed code into our repository.

### CODE REVIEW

**Comment by bollu** [comment]
CC @ChrisHughes24 @tobiasgrosser @alexkeizer @Kha. 

Could you write:

> I agree with this license change.

if you agree with the change in license?

**Comment by tobiasgrosser** [comment]
I agree with this license change.

**Comment by alexkeizer** [comment]
I agree with this license change.

**Comment by lephe** [comment]
I agree with this license change.
Bonus points if there is still any traces of the code I wrote in the repo

**Comment by Kha** [comment]
I agree with this license change.

**Comment by ChrisHughes24** [comment]
I agree with this license change.

**Comment by bollu** [comment]
Great, feel invited to merge @tobiasgrosser , I believe we have agreement from everyone who’s edited the code.

**Pull request merged**
