### PR TITLE
Optimize the kernels in AliveStatements

### PR DESCRIPTION
**Pull request by tobiasgrosser**
This gives us 48 out of 90 statements proven (42 sorry-ed).

### CODE REVIEW

**Comment by bollu** [comment]
@tobiasgrosser you seem to be adding `simp` again, do we not want `simp only [theorem1, ..., theoremN]` or `simp only [simp_set]`?

**Comment by tobiasgrosser** [comment]
Let's start with the simps. If it becomes clearer what these actually are, we can factor this into a simp_set.

> @tobiasgrosser you seem to be adding `simp` again, do we not want `simp only [theorem1, ..., theoremN]` or `simp only [simp_set]`?

Is there a way to add `ofInt_eq_ofNat` via a simp set? I tried, but I cannot add the `()`. 😢

**Comment by tobiasgrosser** [comment]
Otherwise, I feel `negOne_eq_allOnes : -1#w = allOnes w` is inconsistent in lean. We should either rewrite to allOnes or state our theorems as -1#w.

**Comment by tobiasgrosser** [comment]
I feel in absence of new ideas of to cleanup this code (with respect to the questions above) this is ready to merge.

**Comment by tobiasgrosser** [comment]
I think we should just move ahead with this. I don't think I want to add another zulip discussion cycle.

**Pull request merged**
