### PR TITLE
feat: upstream a handwritten proof for alive - alive_DivRemOfSelectLarge proofs one

### PR DESCRIPTION
**Pull request by tobiasgrosser**
This proof is factored out of https://github.com/opencompl/ssa/pull/167 and is part of a collection of proofs that we manually wrote to demonstrate the status of leans automation in BitVectors and such.

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
The com-wrapper diff has been PRed separately at https://github.com/opencompl/ssa/pull/261.

**Comment by tobiasgrosser** [comment]
Rebased on `main`.

**Comment by bollu** [comment]
@tobiasgrosser LGTM to me, I golfed the proof.

**Comment by tobiasgrosser** [comment]
Should we wait for @alexkeizer to give it a review?

**Comment by bollu** [comment]
It looks good to me, this is the type of thing I'd be happy to have a post-commit review on wrt proof golfing techniques from @alexkeizer and @goens :)

**Comment by tobiasgrosser** [comment]
OK. Then let's merge, and I will prepare another PR. 😄 Thank you for the fast turnaround.

**Pull request merged**
